<a href="https://colab.research.google.com/github/ML20220207/TFbasics/blob/main/01_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # find the version number (should be 2.x+)

2.7.0


In [2]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [3]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [4]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [5]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

 *   tf.matmul(X, Y) ('@' in python)
 *   tf.reshape(Y, shape=(2, 3))
 *   tf.transpose(X)
 *   tf.tensordot()
 *   B = tf.cast(B, dtype=tf.float16)




*    tf.square() - get the square of every value in a tensor.
*    tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
*    tf.math.log() - get the natural log of every value in a tensor (elements need to floats).



*   tf.reduce_min() - find the minimum value in a tensor.
*   tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
*   tf.reduce_mean() - find the mean of all elements in a tensor.
*   tf.reduce_sum() - find the sum of all elements in a tensor.

*    tf.argmax() - find the position of the maximum element in a given tensor.
*    tf.argmin() - find the position of the minimum element in a given tensor.

### ✅***Squeezing a tensor:***

In [7]:
import numpy as np 
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim


(TensorShape([1, 1, 1, 1, 50]), 5)

In [8]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

### ✅***One-hot encoding***


In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

In [ ]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

### ✅***Manipulating tf.Variable tensors***

In [12]:
I = tf.Variable(np.arange(0, 5))
I.assign([0, 1, 2, 3, 50])
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [13]:
# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10])
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

### ✅***Tensors and NumPy***

*    np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).
*    tensor.numpy() - call on a tensor to convert to an ndarray.

In [ ]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

In [15]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

### ✅***Using @tf.function***
In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).


```
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)
```



### ✅***Finding access to GPUs***

In [ ]:
print(tf.config.list_physical_devices('GPU'))
!nvidia-smi